### ISSUE TITLE
400 Badrequest - expeced filesize xx got yy

### ISSUE THREAD

**Issue by madchap** [owncloud-docker/server#18]
Hi,

Using the latest container version today, I encounter that error that seemed to make quite some noise for a few years now. I've tried some of the workarounds offered on the internet, to no avail.

It happens to me here whereas the server and client are in home networks (server is 192.168.10.xx and client at 192.168.20.xx).Network stability is ok.

Given this is a container that should work out of the box, I am considering this to be an issue.

Running sqlite in the backend (2 users, few files, yet usually bigger size files around 1Gb).

Image:
owncloud/server                      latest              a4f1b7ecb761        9 days ago          745MB

Thanks,
fred

```
{"reqId":"visWv1oOtQJwdW6h66AU","level":4,"time":"2017-09-02T10:23:35+00:00","remoteAddr":"34.34.54.23","user":"xxxxx","app":"webdav","method":"PUT","url":"\/remote.php\/webdav\/xxxxxx.mp4","message":"Exception: {\"Message\":\"HTTP\\\/1.1 400 expected filesize 549163863 got 3653632\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\BadRequest\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(158): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #57)\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1095): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile('All_HANDS_2016-...', Resource id #57)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(525): Sabre\\\\DAV\\\\Server->createFile('KS\\\/All_HANDS_20...', Resource id #57, NULL)\\n#3 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(63): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/www\\\/owncloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/ownclo...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php\",\"Line\":156,\"User\":\"xxxxx\"}"}
```

**Comment by tboerger** [comment]
Thank you for the report, but this looks like a core issue and not directly related to the docker container, so please report this on the core repository.
